#!/usr/bin/env python
import sys
import os
m=sys.argv[1].index('+')
estr="nm "+sys.argv[2]+" | grep "+str(sys.argv[1][:m])+" | awk '{print $1}' | head -1"
#print estr
address=[a for a in os.popen(estr)]
address=address[0][:len(address[0])-1]
hexstr=hex(int(address,16)+int(sys.argv[1][m+1:],16))
estr="addr2line -e "+sys.argv[2]+" "+hexstr
#print estr
os.system(estr)
